FROM python:3.12-alpine

ENV PYTHONUNBUFFERED=1

# Install system dependencies like Poppler
RUN apk add --no-cache poppler-utils

# Set working dir in container
WORKDIR /app

# Python Packages
COPY requirements.txt .

# Install python packages
RUN pip install --no-cache-dir -r requirements.txt 

# Copy the rest code from the worker
COPY . .

# Running the worker script
CMD [ "python", "main.py" ]

